INSERT INTO TB_DEPARTAMENT (NAME) VALUES ('Gestão'); 
INSERT INTO TB_DEPARTAMENT (NAME) VALUES ('Informática');

INSERT INTO TB_USER (DEPARTMENT_ID, NAME, EMAIL)
SELECT d.ID, 'Maria', 'maria@gmail.com' FROM TB_DEPARTAMENT d WHERE d.NAME='Gestão';

INSERT INTO TB_USER (DEPARTMENT_ID, NAME, EMAIL)
SELECT d.ID, 'Bob', 'bob@gmail.com' FROM TB_DEPARTAMENT d WHERE d.NAME='Gestão';

INSERT INTO TB_USER (DEPARTMENT_ID, NAME, EMAIL)
SELECT d.ID, 'Alex', 'alex@gmail.com' FROM TB_DEPARTAMENT d WHERE d.NAME='Informática';

INSERT INTO TB_USER (DEPARTMENT_ID, NAME, EMAIL)
SELECT d.ID, 'Ana', 'ana@gmail.com' FROM TB_DEPARTAMENT d WHERE d.NAME='Informática';
